name: Build Overlays

on:
  push:
    branches: [ main ]
    paths:
      - 'index.js'
      - 'start.sh'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:0.20230405.47175
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Build
      run: ./start.sh
    - name: Commit overlays
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A overlays
        git commit -m "Update overlays"
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
