name: Test Engine

on:
  pull_request:
    paths:
      - 'index.js'
      - 'start.sh'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:0.20230405.47175
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: ./start.sh
