name: Test Overlays

on:
  pull_request:
    paths:
      - 'index.js'
      - 'start.sh'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:3.0.20250306.120299
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: ./start.sh
